version: '27.0.3'

services:

  db:
    image: postgres:15.2
    container_name: container_database_postgres
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=db-postgres-jberdeja
      - POSTGRES_USER=jhonny
      - POSTGRES_PASSWORD=clavejhonny
    ports:
      - "5434:5432"